[Distribution]
Distribution=arch
Release=rolling
Architecture=x86-64
Mirror=https://archive.archlinux.org/repos/2026/05/01

[Output]
Format=disk
ImageId=arch-gnome
Output=arch-gnome
CompressOutput=no

[Content]
Bootable=yes
Bootloader=systemd-boot
KernelCommandLine=root=PARTLABEL=root-a rw systemd.gpt_auto=no
Hostname=arch-gnome
Timezone=Europe/Paris
Locale=en_US.UTF-8
Keymap=us
Packages=
        base
        linux
        linux-firmware
        systemd
        systemd-sysvcompat
        sudo
        networkmanager
        accountsservice
        gdm
        gnome
        gnome-initial-setup
        ptyxis
        firefox
        cups
        xdg-user-dirs
        pipewire
        pipewire-alsa
        pipewire-pulse
        pipewire-jack
        wireplumber
        mesa
        vulkan-radeon
        vulkan-intel
        qemu-guest-agent

RemovePackages=
        decibels
        epiphany
        evince
        gnome-backgrounds
        gnome-characters
        gnome-connections
        gnome-console
        gnome-remote-desktop
        gnome-tour
        gnome-user-share
        showtime
        simple-scan
        snapshot
        sushi
