[Partition]
Type=esp
Label=esp
Format=vfat
SizeMinBytes=1G
SizeMaxBytes=1G
CopyFiles=/efi/EFI:/EFI
CopyFiles=/efi/loader:/loader
CopyFiles=/boot/EFI:/EFI
CopyFiles=/boot/loader:/loader
CopyFiles=/boot/arch-gnome:/arch-gnome
