[Partition]
Type=root
Label=root-a
Format=ext4
CopyFiles=/
ExcludeFiles=/var
ExcludeFiles=/home
MakeDirectories=/var /home
Minimize=guess
SizeMinBytes=8G
SizeMaxBytes=8G
ReadOnly=yes
GrowFileSystem=no
