[Partition]
Type=linux-generic
Label=root-b
Format=ext4
SizeMinBytes=6G
SizeMaxBytes=6G
CopyFiles=/
ExcludeFiles=/efi /var /home /usr/lib/ab-boot/slot /usr/lib/ab-boot/slot-seeds
MakeDirectories=/efi /var /home /usr/lib/ab-boot
CopyFiles=/usr/lib/ab-boot/slot-seeds/root-b/slot:/usr/lib/ab-boot/slot
